# NOTE: This file is a work in progress.
# The information here reflected is provisional
# and must not be interpreted as the ground truth.
# yaml-language-server: $schema=./teams.schema.json
name: conda-maintainers
description: Maintainers of `conda` and related core plugins
charter: project
requirements:
resources:
  teams:
    - conda/conda-maintainers
  repos:
    - conda/conda
    - conda/conda-libmamba-solver
    - conda/conda-classic-solver
  other:
links:
  - https://github.com/conda/conda/issues/13526
members:
  beeankha: https://github.com/conda/conda/issues/13526
  chenghlee: https://github.com/conda/conda/issues/13526
  danyeaw: https://github.com/conda/governance/issues/265
  dholth: https://github.com/conda/conda/issues/13526
  ForgottenProgramme: https://github.com/conda/conda/issues/13526
  george-lorch: https://github.com/conda/governance/issues/216
  jaimergp: https://github.com/conda/conda/issues/13526
  jezdez: https://github.com/conda/conda/issues/13526
  jjhelmus: https://github.com/conda/governance/issues/219
  kenodegard: https://github.com/conda/conda/issues/13526
  mbargull: https://github.com/conda/conda/issues/13526
  ryanskeith:
  soapy1: https://github.com/conda/governance/issues/258
  travishathaway: https://github.com/conda/conda/issues/13526
emeritus:
