# yaml-language-server: $schema=./teams.schema.json
name: conda-tasks
description: The teams that maintains conda-tasks
charter: incubated-project
details:
resources:
  teams:
    - conda-incubator/conda-tasks
  repos: []
  other:
links: []
members:
  jezdez:
emeritus:
