# yaml-language-server: $schema=./teams.schema.json
name: conda-pack
description: The team maintaining conda-pack
charter: community-project
details:
resources:
  teams:
    - conda/conda-pack
  repos:
    - conda/conda-pack
  other:
links: []
members:
  msarahan:
  ryanskeith:
  xhochy:
emeritus:
