# NOTE: This file is a work in progress.
# The information here reflected is provisional
# and must not be interpreted as the ground truth.
# yaml-language-server: $schema=./teams.schema.json
name: conda-tree
description: Maintainers of `conda-tree`
charter: project
requirements:
resources:
  teams:
    - conda-incubator/conda-tree
  repos:
    - conda-incubator/conda-tree
  other:
links:
  - https://github.com/conda-incubator/conda-tree/issues/20
members:
  rvalieris: https://github.com/conda-incubator/conda-tree/issues/20
emeritus:
