# NOTE: This file is a work in progress.
# The information here reflected is provisional
# and must not be interpreted as the ground truth.
# yaml-language-server: $schema=./teams.schema.json
name: conda-tui
description: Maintainers of `conda-tui`
charter: dynamic
requirements:
resources:
  teams:
    - conda-incubator/conda-tui
  repos:
    - conda-incubator/conda-tui
  other:
links:
  - https://github.com/conda/governance/issues/108
members:
  chenghlee: https://github.com/conda/governance/issues/108
  mattkram: https://github.com/conda/governance/issues/108
emeritus:
