# NOTE: This file is a work in progress.
# The information here reflected is provisional
# and must not be interpreted as the ground truth.
# yaml-language-server: $schema=./teams.schema.json
name: conda-oci
description: Maintainers of `conda-oci`
charter:
requirements:
resources:
  teams:
    - conda-incubator/conda-oci
  repos:
    - conda-incubator/conda-oci
  other:
links:
members:
  beckermr:
  jezdez:
emeritus:
