# yaml-language-server: $schema=./teams.schema.json
name: conda-workspaces
description: The team maintaining conda-workspaces
charter: incubated-project
details:
resources:
  teams:
    - conda-incubator/conda-workspaces
  repos:
    - conda-incubator/conda-workspaces
  other:
links: []
members:
  jezdez:
emeritus:
