# NOTE: This file is a work in progress.
# The information here reflected is provisional
# and must not be interpreted as the ground truth.
# yaml-language-server: $schema=./teams.schema.json
name: conda-rattler-solver
description: Maintainers of `conda-rattler-solver`
charter: dynamic
requirements:
resources:
  teams:
    - conda-incubator/conda-rattler-solver
  repos:
    - conda-incubator/conda-rattler-solver
  other:
links:
  - https://github.com/conda/governance/issues/246
members:
  jaimergp: https://github.com/conda/governance/issues/246
  jezdez: https://github.com/conda-incubator/conda-rattler-solver/issues/18
emeritus:
