# NOTE: This file is a work in progress.
# The information here reflected is provisional
# and must not be interpreted as the ground truth.
# yaml-language-server: $schema=./teams.schema.json
name: conda-store
description: Maintainers of `conda-store` and related projects
charter: dynamic
requirements:
resources:
  teams:
    - conda-incubator/conda-store
  repos:
    - conda-incubator/conda-store
    - conda-incubator/conda-store-ui
    - conda-incubator/jupyterlab-conda-store
  other:
links:
  - https://github.com/conda/governance/issues/106
members:
  dharhas: https://github.com/conda/governance/issues/106
  gabalafou: https://github.com/conda/governance/issues/106
  jaimergp: https://github.com/conda/governance/issues/106
  kcpevey: https://github.com/conda/governance/issues/106
  pavithraes: https://github.com/conda/governance/issues/106
  peytondmurray:
  smeragoel: https://github.com/conda/governance/issues/106
  soapy1:
  trallard: https://github.com/conda/governance/issues/106
  viniciusdc: https://github.com/conda-incubator/conda-store/issues/1115
emeritus:
  aktech:
  anirrudh:
  asmeurer:
  costrouc:
  iameskild:
  pierrotsmnrd:
  steff456:
