# yaml-language-server: $schema=./teams.schema.json
name: conda-global
description: The team working on conda-global
charter: incubated-project
details:
resources:
  teams:
    - conda-incubator/conda-global
  repos:
    - conda-incubator/conda-global
  other:
links: []
members:
  jezdez:
emeritus:
