# yaml-language-server: $schema=./teams.schema.json
name: conda-tutorial
description: Maintainers of the `conda-tutorial` repository
charter:
requirements:
resources:
  teams:
    - conda-incubator/conda-tutorial
  repos:
    - conda-incubator/conda-tutorial
  other:
links:
members:
  beeankha:
  jezdez:
  leriomaggio:
  tnabtaf:
emeritus:
