# NOTE: This file is a work in progress.
# The information here reflected is provisional
# and must not be interpreted as the ground truth.
# yaml-language-server: $schema=./teams.schema.json
name: conda-mirror
description: Maintainers of `conda-mirror`
charter:
requirements:
resources:
  teams:
    - conda-incubator/conda-mirror
  repos:
    - conda-incubator/conda-mirror
  other:
links:
members:
  delsner:
  ericdill:
  goanpeca:
  mariusvniekerk:
  pavelzw:
  scopatz:
  xhochy:
emeritus:
