# NOTE: This file is a work in progress.
# The information here reflected is provisional
# and must not be interpreted as the ground truth.
# yaml-language-server: $schema=./teams.schema.json
name: conda-maintainers-project-management
description: A team for organizing the project management for conda-maintainers
charter: dynamic
requirements:
resources:
  teams:
    - conda/conda-maintainers-project-management
  repos: []
  other:
links: []
members:
  george-lorch:
  jaimergp:
  jezdez:
  lwinfree:
  trallard:
emeritus:
