# NOTE: This file is a work in progress.
# The information here reflected is provisional
# and must not be interpreted as the ground truth.
# yaml-language-server: $schema=./teams.schema.json
name: conda-rich
description: Maintainers of `conda-rich`
charter: dynamic
requirements:
resources:
  teams:
    - conda-incubator/conda-rich
  repos:
    - conda-incubator/conda-rich
  other:
links:
  - https://github.com/conda/governance/issues/191
members:
  jezdez: https://github.com/conda/governance/issues/191
  travishathaway: https://github.com/conda/governance/issues/191
emeritus:
