# NOTE: This file is a work in progress.
# The information here reflected is provisional
# and must not be interpreted as the ground truth.
# yaml-language-server: $schema=./teams.schema.json
name: security
description: The security response coordination team
charter: static-subteam
details: |
  ## Role

  The mission of this team is to act as a coordination body
  among the different projects hosted in the conda and
  conda-incubator organizations.

  ## Responsibility

  ...

  ## Membership

  Any active steering council member may join without approval.
  Non-council members can be added via a vote (sensitive, threshold of 50%).

  ## More information

  For more information see https://github.com/conda/security.
resources:
  teams:
    - conda-incubator/security
    - conda/security
  repos:
    - conda-incubator/security
    - conda/security
  other:
links:
  - PENDING
members:
  jaimergp: PENDING
  jezdez: PENDING
emeritus:
