# ignore meeting notes since they are synced as is from HackMD
exclude: |
  (?x)^(
    meetings/archive
  )/
repos:
  - repo: local
    hooks:
      - id: pixi-install
        name: pixi-install
        entry: pixi install
        language: system
        always_run: true
        require_serial: true
        pass_filenames: false
      # ruff
      - id: ruff
        name: ruff
        entry: pixi run ruff check --fix --exit-non-zero-on-fix --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: pixi run ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
      # pre-commit-hooks
      - id: trailing-whitespace-fixer
        name: trailing-whitespace-fixer
        entry: pixi run trailing-whitespace-fixer
        language: system
        types: [text]
      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: pixi run end-of-file-fixer
        language: system
        types: [text]
      - id: check-merge-conflict
        name: check-merge-conflict
        entry: pixi run check-merge-conflict --assume-in-merge
        language: system
        types: [text]
      - id: mixed-line-ending
        name: mixed-line-ending
        entry: pixi run mixed-line-ending
        language: system
        types: [text]
      - id: check-toml
        name: check-toml
        entry: pixi run check-toml
        language: system
        types: [toml]
      - id: check-yaml
        name: check-yaml
        entry: pixi run check-yaml
        language: system
        types: [yaml]
      # check-jsonschema
      - id: check-jsonschema
        name: check-jsonschema
        entry: pixi run check-jsonschema
        language: system
        types: [json,yaml]
        files: ^teams/.*\.ya?ml$
        args: [--schemafile, teams/teams.schema.json]
      - id: check-github-workflows
        name: check-github-workflows
        entry: pixi run check-jsonschema --builtin-schema vendor.github-workflows
        language: system
        types: [yaml]
        files: ^\.github/workflows/[^/]+$
      # codespell
      - id: codespell
        name: codespell
        entry: pixi run codespell
        language: system
        exclude_types: [csv]
        types: [text]
        args: [--write-changes]
      # zizmor
      - id: zizmor
        name: zizmor
        entry: pixi run zizmor --min-severity high --fix .
        language: system
        types: [yaml]
        pass_filenames: false


  # - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  #   rev: v2.16.0
  #   hooks:
  #     - id: pretty-format-toml
  #       args: [--autofix, --trailing-commas]
  # - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  #   rev: 0.2.3
  #   hooks:
  #     - id: yamlfmt
  #       # ruamel.yaml doesn't line wrap correctly (?) so set width to 1M to avoid issues
  #       args: [--mapping=2, --offset=2, --sequence=4, --width=1000000, --implicit_start]
