name: Join/Leave Steering Council
description: Use this template to request joining or leaving the Steering Council.
title: Request to Join/Leave Steering Council
body:
  - type: markdown
    attributes:
      value: |
        ## Basic Information
        > [!NOTE]
        > Members who leave the Steering Council are moved to emeritus status. See [Conda Governance](https://github.com/conda/governance#emeritus-steering) for details.
  - type: input
    id: username
    attributes:
      label: GitHub Username
      description: Provide the GitHub username of the user to be added or removed from the Steering Council.
    validations:
      required: true
  - type: dropdown
    id: action
    attributes:
      label: Request Type
      description: Select whether you are requesting to join or leave the Steering Council.
      options:
        - Join
        - Leave
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Additional Information
  - type: textarea
    id: reason
    attributes:
      label: Reason for Request
      description: Provide a brief explanation of why you are requesting to join or leave the Steering Council.
    validations:
      required: true
