name: Nominate to Steering Council
description: Use this form to nominate yourself or someone else to the conda Steering Council.
title: '[Steering Council Nomination]: '

body:
  - type: markdown
    attributes:
      value: |
        ## Steering Council Nomination

        Use this form to nominate a new member to the Steering Council (including self-nominations).

        Please refer to the [conda Governance documentation](https://github.com/conda/governance#steering-council) for information about Steering Council responsibilities and qualifications.

  - type: input
    id: username
    attributes:
      label: GitHub Username
      description: The GitHub username of the person being nominated.
    validations:
      required: true

  - type: textarea
    id: qualifications
    attributes:
      label: Qualifications & Contributions
      description: Describe the nominee's contributions to the conda ecosystem and qualifications for the Steering Council.
    validations:
      required: true
