name: Nominate to Steering Council or Move to/from Emeritus Steering
description: Use this form to self-nominate or nominate others to the Steering Council, or request moving to/from Emeritus Steering.
title: Nominate to Steering Council or Move to/from Emeritus Steering
body:
  - type: markdown
    attributes:
      value: |
        ## Basic Information
        See [Steering Council](https://github.com/conda/governance#steering-council) and [Emeritus Steering](https://github.com/conda/governance#emeritus-steering) for details on the membership roles.

        > [!NOTE]
        > Use this form to self-nominate or nominate others to the Steering Council, or request moving to/from Emeritus Steering.
  - type: input
    id: username
    attributes:
      label: GitHub Username
      description: Provide the GitHub username of the user to be nominated to the Steering Council or to become an Emeritus Steering member.
    validations:
      required: true
  - type: dropdown
    id: action
    attributes:
      label: Request Type
      description: Select whether this is a nominiation to the Steering Council or whether this is moving an existing member to/from Emeritus Steering.
      options:
        - Nomination to Steering
        - Steering to Emeritus
        - Emeritus to Steering
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Additional Information
  - type: textarea
    id: reason
    attributes:
      label: Reason for Request
      description: Provide a brief explanation of why you are submitting this request.
    validations:
      required: true
