# yaml-language-server: $schema=../teams.schema.json
name: conda/conda-dot-org
description: Team responsible for the conda.org website maintenance
charter:
requirements:
scopes:
  codeowners:
    - conda/conda-dot-org
  other:
links:
members:
  jezdez:
  travishathaway:
  jaimergp:
  beeankha:
  kathatherine:
emeritus:
