# yaml-language-server: $schema=../teams.schema.json
name: conda/conda-maintainers
description: Maintainers of `conda` and related core plugins
charter: project
requirements:
scopes:
  codeowners:
    - conda/conda
    - conda/conda-libmamba-solver
    - conda/conda-classic-solver
  other:
links:
  - https://github.com/conda/conda/issues/13526
members:
  jezdez: https://github.com/conda/conda/issues/13526
  dholth: https://github.com/conda/conda/issues/13526
  ryanskeith:
  travishathaway: https://github.com/conda/conda/issues/13526
  soapy1: https://github.com/conda/governance/issues/258
  jjhelmus: https://github.com/conda/governance/issues/219
  jaimergp: https://github.com/conda/conda/issues/13526
  chenghlee: https://github.com/conda/conda/issues/13526
  kenodegard: https://github.com/conda/conda/issues/13526
  george-lorch: https://github.com/conda/governance/issues/216
  danyeaw: https://github.com/conda/governance/issues/265
  mbargull: https://github.com/conda/conda/issues/13526
  beeankha: https://github.com/conda/conda/issues/13526
  ForgottenProgramme: https://github.com/conda/conda/issues/13526
emeritus:
