# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-rattler-solver
description: Maintainers of `conda-rattler-solver`
charter: dynamic
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-rattler-solver
  other:
links:
  - https://github.com/conda/governance/issues/246
members:
  jaimergp: https://github.com/conda/governance/issues/246
  jezdez: https://github.com/conda-incubator/conda-rattler-solver/issues/18
emeritus:
