# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-tree
description: Maintainers of `conda-tree`
charter: project
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-tree
  other:
links:
  - https://github.com/conda-incubator/conda-tree/issues/20
members:
  rvalieris: https://github.com/conda-incubator/conda-tree/issues/20
emeritus:
