# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-spawn
description: Maintainers of `conda-spawn`
charter: dynamic
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-spawn
  other:
links:
  - https://github.com/conda/governance/issues/202
members:
  jaimergp: https://github.com/conda/governance/issues/202
emeritus:
