# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-oci
description: Maintainers of `conda-oci`
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-oci
  other:
links:
members:
  jezdez:
  beckermr:
emeritus:
