# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-rich
description: Maintainers of `conda-rich`
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-rich
  other:
links:
members:
  jezdez:
  travishathaway:
emeritus:
