# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-tree
description: Maintainers of `conda-tree`
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-tree
  other:
links:
members:
  rvalieris:
emeritus:
