# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-spawn
description: Maintainers of `conda-spawn`
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-spawn
  other:
links:
members:
  jaimergp:
emeritus:
