# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-meta-mcp
description:
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-meta-mcp
  other:
links:
members:
  jezdez:
  dbast:
emeritus:
