# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-sh
description: Maintainers of the conda.sh website
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda.sh
  other:
links:
members:
  Carreau:
  jaimergp:
  jezdez:
emeritus:
