# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-tui
description: Maintainers of `conda-tui`
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-tui
  other:
links:
members:
  chenghlee:
  mattkram:
emeritus:
