# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-colab
description: Maintainers of `condacolab`
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/condacolab
  other:
links:
members:
  jaimergp:
  ssurbhi560:
emeritus:
