# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-tutorial
description: Maintainers of the `conda-tutorial` repository
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-tutorial
  other:
links:
members:
  jezdez:
  tnabtaf:
  leriomaggio:
  beeankha:
emeritus:
