# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-store
description: Maintainers of `conda-store` and related projects
charter: dynamic
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-store
    - conda-incubator/conda-store-ui
    - conda-incubator/jupyterlab-conda-store
  other:
links:
  - https://github.com/conda/governance/issues/106
members:
  gabalafou: https://github.com/conda/governance/issues/106
  dharhas: https://github.com/conda/governance/issues/106
  soapy1:
  jaimergp: https://github.com/conda/governance/issues/106
  peytondmurray:
  kcpevey: https://github.com/conda/governance/issues/106
  trallard: https://github.com/conda/governance/issues/106
  pavithraes: https://github.com/conda/governance/issues/106
  smeragoel: https://github.com/conda/governance/issues/106
  viniciusdc: https://github.com/conda-incubator/conda-store/issues/1115
emeritus:
  pierrotsmnrd:
  costrouc:
  aktech:
  anirrudh:
  iameskild:
  steff456:
  asmeurer:
