# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-project
description: Maintainers of `conda-project`
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-project
  other:
links:
members:
  AlbertDeFusco:
  jbednar:
  jezdez:
  jkong-anaconda:
  jlstevens:
  mattkram:
emeritus:
