# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/condastats
description: Maintainers of `condastats`
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/condastats
  other:
links:
members:
  jezdez:
  sophiamyang:
emeritus:
