# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-plugins
description: Maintainers of `conda-plugins`
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-plugins
  other:
links:
members:
  jezdez:
  travishathaway:
  kenodegard:
  beeankha:
emeritus:
