# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-checkpoints
description: Maintainers of `conda-checkpoints`
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-checkpoints
  other:
links:
members:
  jaimergp:
emeritus:
