# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-subchannel
description: Maintainers of `conda-subchannel`
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-subchannel
  other:
links:
members:
  jezdez:
  jaimergp:
emeritus:
