# yaml-language-server: $schema=../teams.schema.json
name: conda-incubator/conda-protect
description: Maintainers of `conda-protect`
charter:
requirements:
scopes:
  codeowners:
    - conda-incubator/conda-protect
  other:
links:
members:
  jezdez:
  travishathaway:
emeritus:
