name: Teams

on:
  workflow_dispatch:
  pull_request:
    paths:
      - teams/**/*.yml
      - teams/*.yml
      - teams/**/*.yaml
      - teams/*.yaml
      - teams/*.schema.json
      - scripts/check_teams.py
      - scripts/schemas.py
      - scripts/sort_team_yaml.py
      - .github/workflows/check-teams.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
      - run: pixi run check_teams
        env:
          CONDA_ORG_WIDE_TOKEN: ${{ secrets.CONDA_ORG_WIDE_READ_ONLY }}
          CONDA_INCUBATOR_ORG_WIDE_TOKEN: ${{ secrets.CONDA_INCUBATOR_ORG_WIDE_READ_ONLY }}
