name: CI
on:
  pull_request:
  push:
    branches:
      - main
# Automatically stop old builds on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    permissions:
      contents: read
    name: Lint
    timeout-minutes: 10
    runs-on: ubuntu-slim
    steps:
      - name: Checkout branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
      - name: Run linting
        run: pixi run lint --color=always --show-diff-on-failure
